### ISSUE TITLE
Lightning Spell Decal

### ISSUE THREAD

**Issue by AlekseyPanas** [AlekseyPanas/CSC404_Magengaard#31]
A semi-transparent 2D decal applied to a surface representing something that would look like lightning damage

Notice the blackened ground region under the spell in this LoL image.
![Image](https://github.com/AlekseyPanas/CSC404_Magengaard/assets/47086586/6f62def5-8680-4312-9f9a-0324e533c330)

**Comment by PyroPoro** [comment]
I was thinking something like this instead
https://streamable.com/mc1at1

**Comment by PyroPoro** [comment]
This is Viktor's R ability from league of legends. I plan to have the spell slowly follow the nearest enemy
